
version: 2
jobs:
  py35-tests: &test-template
    docker:
      - image: circleci/python:3.5
      - image: mysql:5.6.33
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=django_auditor
    environment:
      - TOX_ENV=py35-django110
    steps:
      - checkout
      - run:
          name: Setup a virtualenv
          command: virtualenv venv
      - run:
          name: Run tests with tox
          command: |
            source venv/bin/activate
            pip install tox
            echo $TOX_ENV | tr ";" "\n" | xargs -L 1 -I % tox -e $TOX_ENV

workflows:
  version: 2
  pr-checks:
    jobs:
      - py35-tests
