name: Test With Various Python/Django Versions
on: [push]

# Cancel running workflows for this same branch on each push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Jobs
jobs:
  py-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10.15, 3.11]
        django-version: [40, 41, 42, 50, 51]
        exclude:
          - python-version: 3.9
            django-version: 50
          - python-version: 3.9
            django-version: 51
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Run tests with tox
        run: tox -e django${{ matrix.django-version }}
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ./coverage.xml
